### ISSUE TITLE
HTTP Support from Protocols

### ISSUE THREAD

**Issue by juanpedromoreno** [higherkindness/mu-scala#182]
**`frees-rpc` is for RPC**. 

Having said that, it'd be great supporting the creation of HTTP/REST endpoints taking advantage of the RPC service implementations. This is mandatory in some cases/environments when the HTTP/REST API is the only way possible.

This is related to #73, but focuses on the scenario of HTTP/REST on both ends instead of a REST<->gRPC converter or proxy.

Subtasks:

* [x] Naming. A module named `frees-rpc-http` is implemented in #203. Ideally we'll want to settle on a naming convention for the feature such as HTTP, REST or HTTP/REST. 
* Transport Implementation
  * [x] Transport/Framework layer implementation. Our current approach is to use [http4s](https://github.com/http4s/http4s) and its DSL, as implemented [here](https://github.com/frees-io/freestyle-rpc/commit/bb9f8a4d5afd139542bf3b77a1c116a60fbdcbaf).
  * [x] FS2 streaming support. Supported by http4s, mainly for server-streaming but client/bidi streaming is also possible, and implemented [here](https://github.com/frees-io/freestyle-rpc/commit/bb9f8a4d5afd139542bf3b77a1c116a60fbdcbaf#diff-1835d06e0faa670afb3c0610ecfb02ce).
  * [x] Monix/Observable streaming support. Reversing the gRPC-based approach in the main project, we can convert FS2 to Monix internally, as implemented [here](https://github.com/frees-io/freestyle-rpc/commit/3666518a658522a1d0ebfd7bb04bf009644337f4).
  * [x] Error handling. Just as with RPC, we'll want to support error raising in monadic (`MonadError`) and streaming contexts (keeping in mind that a stream can start OK and end in error). The sample implementation [here](https://github.com/frees-io/freestyle-rpc/commit/9711c2b276bf3c16c6231295b2369673901fa6e0) accepts gRPC's thrown `Status[Runtime]Exception` for triggering specific return codes, but we'll probably want to provide a more generic type of error for this.
  * [ ] HTTP/2 support: Http4s supports this on the server side (requires TLS) but the state of client-side support is less clear. This is tracked in #205.
* Endpoint Derivation
  * [ ] Annotations/DSL to define HTTP endpoints and registering the different routes; there are some ideas in #73. In any case, we'll need macro support to process them for server/client derivation, and we're holding off on macro-based development until we've decided on a new codegen system for freestyle[-rpc], as discussed in https://github.com/frees-io/freestyle/issues/539. 
  * [ ] Http Server Derivation. By processing the annotations we'll want to end up with something like [this](https://github.com/frees-io/freestyle-rpc/blob/feature/182-http-support-from-protocols/modules/http/server/src/test/scala/GreeterRestServices.scala).
  * [x] Http Client Derivation. As above, for something like [this](https://github.com/frees-io/freestyle-rpc/blob/feature/182-http-support-from-protocols/modules/http/server/src/test/scala/GreeterRestClients.scala).  Work being done in https://github.com/frees-io/freestyle-rpc/pull/368
  * [ ] Multi-server bootstrapping. We need to provide utilities and helpers to start/shutdown both server RPC and HTTP servers (obviously on different ports).
* Endpoint Documentation
  * [x] Open API/Swagger. Open-API 3.0 (implemented in Swagger 2.0) seems promising, but the Scala tools to generate it are not ideal currently. Http4s has it in the [rho](https://github.com/http4s/rho) project, but very closely tied to its DSL. [Swagger-scala-module](https://github.com/swagger-api/swagger-scala-module) supports message classes but not services, and doesn't support Open-API 3 yet (https://github.com/swagger-api/swagger-scala-module/issues/49). We'll revisit it once it does.

(original text by @juanpedromoreno, last edited by @L-Lavigne)

**Comment by juanpedromoreno** [comment]
This is probably a bit outdated. Closing it for now.
